### ISSUE TITLE
Pulling from remote failed

### ISSUE THREAD

**Issue by bielermi** [zaggino/brackets-git#886]
[I'm supposed to describe steps to replicate my issue here and if I don't do that, I understand that my issue will be probably ignored.]

--------------------------------

*Brackets 1.1.0-15558 (win), Git 1.9.5.msysgit.0 & Brackets-Git 0.14.9*

**Pulling from remote failed**

```
Error: cmd-spawn-timeout: C:\Program Files (x86)\Git\cmd\git.exe merge origin/master
```

```
call: git merge origin/master
Error: cmd-spawn-timeout: C:\Program Files (x86)\Git\cmd\git.exe merge origin/master
    at timeoutPromise (file:///C:/Users/bielermi/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:212:27)
    at file:///C:/Users/bielermi/AppData/Roaming/Brackets/extensions/user/zaggino.brackets-git/src/Cli.js:266:29
```

**Comment by bielermi** [comment]
I'm connected via VPN to my work. On that maschine is my git-repository stored. My speed is about 7000 kbit/s so is think it should be allright. What's the matter? Is it still to slow to get allways a timeout-error?

**Comment by zaggino** [comment]
I have no idea, you can try to execute the same command from command line (git.exe merge origin/master) to see how long it really takes.

**Comment by bielermi** [comment]
I tried that allready. It takes about 3 minutes for a pullws but it works. If it takes a few minutes that's not really a problem. My problem is the cmd-spawn-timeout that comes from brackets-git. 
The command 'git merge origin/master' that created this issue needs only a few seconds in the console.

**Comment by zaggino** [comment]
I'll put in a configurable timeout time to the settings, that should solve it, you can set it to an hour if you want :)

**Comment by bielermi** [comment]
WOW. That should solve the problem.

**Comment by bielermi** [comment]
How can I get your changes? Today I reinstalled your Extension but still can't find this setting. What am I doing wrong?

**Comment by zaggino** [comment]
hi @bielermi , it's not there yet, i'll try to get this done by the end of the week

**Comment by zaggino** [comment]
Brackets Git updated to version 0.14.10.

**Comment by bielermi** [comment]
Thanks a lot!!! That should do the trick.
